### ISSUE TITLE
Houses3k and Omniobject 3d dataset

### ISSUE THREAD

**Issue by IamShubhamGupto** [zjwzcx/GenNBV#3]
Hello! 

Thank you for sharing your amazing work and congratulations on presenting at CVPR 2024! On reading your paper, I am interested the data selection and processing pipeline as described in Sec 4.1. Dataset and Supplementary B. Data Processing. 

Would it be possible to share the code to generate the training and testing sets or even the dataset itself? I am unable to reproduce the 256 object training set just by reading the paper. 

Thanks again

**Comment by zjwzcx** [comment]
> Hello!
> 
> Thank you for sharing your amazing work and congratulations on presenting at CVPR 2024! On reading your paper, I am interested the data selection and processing pipeline as described in Sec 4.1. Dataset and Supplementary B. Data Processing.
> 
> Would it be possible to share the code to generate the training and testing sets or even the dataset itself? I am unable to reproduce the 256 object training set just by reading the paper.
> 
> Thanks again

Thanks for your attention! We'll release our preprocessed dataset (including mesh, gt, ...) within two weeks :)
