### ISSUE TITLE
Questions about 3D Mesh Reconstruction Method in GenNBV

### ISSUE THREAD

**Issue by GitHofee** [zjwzcx/GenNBV#4]
Hello,

First of all, thank you for sharing your impressive work on GenNBV. I have a couple of questions regarding the 3D mesh reconstruction process in your project:

1. Could you please specify the exact method or algorithm you used for 3D mesh reconstruction after obtaining each Next Best View? 

2. When conducting comparative experiments with other baselines, did you use the same 3D mesh reconstruction method for a fair comparison?

Thank you for your time and assistance. I look forward to your response.

**Comment by GitHofee** [comment]
Thank you for your prompt response!

**Comment by GitHofee** [comment]
Thank you for your previous response and the detailed information.  I have a follow-up question regarding the depth maps used for 3D reconstruction:
​Could you please explain how the depth maps required for the reconstruction are obtained?  Are they generated using stereo matching with simulated binocular vision?

**Comment by zjwzcx** [comment]
> Thank you for your previous response and the detailed information. I have a follow-up question regarding the depth maps used for 3D reconstruction:​Could you please explain how the depth maps required for the reconstruction are obtained? Are they generated using stereo matching with simulated binocular vision?

Our depth maps are rendered by our simulator Isaac Gym.
